name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt-get install -y gcc cmake make
    - name: prepare
      run: cmake .
    - name: compilation
      run: make
    - name: test
      run: ./example samples/prince.bmp /tmp/prince-hq2x.bmp 2
